from lxml import etree

from test.utils import assertRaisesError, assertRaises

import dinero
from dinero.gateways.authorizenet import xml_to_dict
from dinero.exceptions import (
    InvalidTransactionError, RefundError, AVSError, CVVError, ExpiryError,
    InvalidAmountError, InvalidCardError, CardDeclinedError,
    DuplicateTransactionError, AuthenticationError, CustomerNotFoundError,
    DuplicateCardError, DuplicateCustomerError,
)


gateway = dinero.get_gateway('authorize.net')


SUCCESSFUL_RESPONSES = (
    # Customer.create
    """<?xml version="1.0" encoding="utf-8"?><createCustomerProfileResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="AnetApi/xml/v1/schema/AnetApiSchema.xsd"><messages><resultCode>Ok</resultCode><message><code>I00001</code><text>Successful.</text></message></messages><customerProfileId>20462960</customerProfileId><customerPaymentProfileIdList><numericString>18753840</numericString></customerPaymentProfileIdList><customerShippingAddressIdList /><validationDirectResponseList /></createCustomerProfileResponse>""",
    # customer.delete
    """<?xml version="1.0" encoding="utf-8"?><deleteCustomerProfileResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="AnetApi/xml/v1/schema/AnetApiSchema.xsd"><messages><resultCode>Ok</resultCode><message><code>I00001</code><text>Successful.</text></message></messages></deleteCustomerProfileResponse>""",
    # Customer.retrieve
    """<?xml version="1.0" encoding="utf-8"?><getCustomerProfileResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="AnetApi/xml/v1/schema/AnetApiSchema.xsd"><messages><resultCode>Ok</resultCode><message><code>I00001</code><text>Successful.</text></message></messages><profile><email>XXXXXX@example.com</email><customerProfileId>20462961</customerProfileId><paymentProfiles><billTo><firstName>Joey</firstName><lastName>Shabadoo</lastName><company>Shabadoo, Inc.</company><address>123 somewhere st</address><city>somewhere</city><state>SW</state><zip>12345</zip><country>US</country><phoneNumber>000-000-0000</phoneNumber><faxNumber>000-000-0001</faxNumber></billTo><customerPaymentProfileId>18753842</customerPaymentProfileId><payment><creditCard><cardNumber>XXXX1111</cardNumber><expirationDate>XXXX</expirationDate></creditCard></payment></paymentProfiles></profile></getCustomerProfileResponse>""",
    # customer.save
    """<?xml version="1.0" encoding="utf-8"?><updateCustomerProfileResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="AnetApi/xml/v1/schema/AnetApiSchema.xsd"><messages><resultCode>Ok</resultCode><message><code>I00001</code><text>Successful.</text></message></messages></updateCustomerProfileResponse>""",
    # retrieve a specific card.
    """<?xml version="1.0" encoding="utf-8"?><getCustomerPaymentProfileResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="AnetApi/xml/v1/schema/AnetApiSchema.xsd"><messages><resultCode>Ok</resultCode><message><code>I00001</code><text>Successful.</text></message></messages><paymentProfile><billTo><firstName>Joey</firstName><lastName>Shabadoo</lastName><company>Shabadoo, Inc.</company><address>123 somewhere st</address><city>somewhere</city><state>SW</state><zip>12345</zip><country>US</country><phoneNumber>000-000-0000</phoneNumber><faxNumber>000-000-0001</faxNumber></billTo><customerPaymentProfileId>18753849</customerPaymentProfileId><payment><creditCard><cardNumber>XXXX1111</cardNumber><expirationDate>XXXX</expirationDate></creditCard></payment></paymentProfile></getCustomerPaymentProfileResponse>""",
    # update a card.
    """<?xml version="1.0" encoding="utf-8"?><updateCustomerPaymentProfileResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="AnetApi/xml/v1/schema/AnetApiSchema.xsd"><messages><resultCode>Ok</resultCode><message><code>I00001</code><text>Successful.</text></message></messages></updateCustomerPaymentProfileResponse>""",
    # create a card.
    """<?xml version="1.0" encoding="utf-8"?><createCustomerPaymentProfileResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="AnetApi/xml/v1/schema/AnetApiSchema.xsd"><messages><resultCode>Ok</resultCode><message><code>I00001</code><text>Successful.</text></message></messages><customerPaymentProfileId>18753852</customerPaymentProfileId></createCustomerPaymentProfileResponse>""",
    # charge_customer
    """<?xml version="1.0" encoding="utf-8"?><createCustomerProfileTransactionResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="AnetApi/xml/v1/schema/AnetApiSchema.xsd"><messages><resultCode>Ok</resultCode><message><code>I00001</code><text>Successful.</text></message></messages><directResponse>1,1,1,This transaction has been approved.,L4Y8BP,Y,2197488381,,,717.21,CC,auth_capture,,,,,,,,,,,,100c75ae-7e8a-4f9c-aff5-7b3d661e80b2@example.com,,,,,,,,,,,,,,B5092A61BC164B7FBD3E6A3816AD3557,,2,,,,,,,,,,,XXXX1111,Visa,,,,,,,,,,,,,,,,</directResponse></createCustomerProfileTransactionResponse>""",
    # charge
    """<?xml version="1.0" encoding="utf-8"?><createTransactionResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="AnetApi/xml/v1/schema/AnetApiSchema.xsd"><messages><resultCode>Ok</resultCode><message><code>I00001</code><text>Successful.</text></message></messages><transactionResponse><responseCode>1</responseCode><authCode>L4Y8BP</authCode><avsResultCode>P</avsResultCode><cvvResultCode /><cavvResultCode /><transId>2197488381</transId><refTransID>2197488381</refTransID><transHash>EA70FD1C33F01AAC9AB586668227FEBF</transHash><testRequest>0</testRequest><accountNumber>XXXX1111</accountNumber><accountType>Visa</accountType><messages><message><code>1</code><description>This transaction has been approved.</description></message></messages></transactionResponse></createTransactionResponse>""",
    # Transaction.retrieve
    """<?xml version="1.0" encoding="utf-8"?><getTransactionDetailsResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="AnetApi/xml/v1/schema/AnetApiSchema.xsd"><messages><resultCode>Ok</resultCode><message><code>I00001</code><text>Successful.</text></message></messages><transaction><transId>2197488386</transId><submitTimeUTC>2013-08-23T15:21:46.58Z</submitTimeUTC><submitTimeLocal>2013-08-23T08:21:46.58</submitTimeLocal><transactionType>authCaptureTransaction</transactionType><transactionStatus>capturedPendingSettlement</transactionStatus><responseCode>1</responseCode><responseReasonCode>1</responseReasonCode><responseReasonDescription>Approval</responseReasonDescription><authCode>CY6A4V</authCode><AVSResponse>Y</AVSResponse><authAmount>256.44</authAmount><settleAmount>256.44</settleAmount><taxExempt>false</taxExempt><payment><creditCard><cardNumber>XXXX1111</cardNumber><expirationDate>XXXX</expirationDate><cardType>Visa</cardType></creditCard></payment><recurringBilling>false</recurringBilling><customerIP>10.1.186.51</customerIP></transaction></getTransactionDetailsResponse>""",
)


PAYMENT_ERRORS = (
    ("""<?xml version="1.0" encoding="utf-8"?><createTransactionResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="AnetApi/xml/v1/schema/AnetApiSchema.xsd"><messages><resultCode>Error</resultCode><message><code>E00027</code><text>The transaction was unsuccessful.</text></message></messages><transactionResponse><responseCode>3</responseCode><authCode /><avsResultCode>P</avsResultCode><cvvResultCode /><cavvResultCode /><transId>0</transId><refTransID /><transHash>XXXXXX</transHash><testRequest>0</testRequest><accountNumber /><accountType /><errors><error><errorCode>33</errorCode><errorText>A valid referenced transaction ID is required.</errorText></error></errors></transactionResponse></createTransactionResponse>""", (InvalidTransactionError,)),
    ("""<?xml version="1.0" encoding="utf-8"?><createTransactionResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="AnetApi/xml/v1/schema/AnetApiSchema.xsd"><messages><resultCode>Error</resultCode><message><code>E00027</code><text>The transaction was unsuccessful.</text></message></messages><transactionResponse><responseCode>3</responseCode><authCode /><avsResultCode>P</avsResultCode><cvvResultCode /><cavvResultCode /><transId>0</transId><refTransID>2197488381</refTransID><transHash>1CA54B5A9D9E12711083F474496BCDA8</transHash><testRequest>0</testRequest><accountNumber>XXXX1111</accountNumber><accountType>Visa</accountType><errors><error><errorCode>54</errorCode><errorText>The referenced transaction does not meet the criteria for issuing a credit.</errorText></error></errors></transactionResponse></createTransactionResponse>""", (RefundError,)),
    ("""<?xml version="1.0" encoding="utf-8"?><createTransactionResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="AnetApi/xml/v1/schema/AnetApiSchema.xsd"><messages><resultCode>Ok</resultCode><message><code>I00001</code><text>Successful.</text></message></messages><transactionResponse><responseCode>2</responseCode><authCode>UURR5X</authCode><avsResultCode>N</avsResultCode><cvvResultCode /><cavvResultCode>2</cavvResultCode><transId>2197488391</transId><refTransID>2197488391</refTransID><transHash>9E27E31FBA54263CBCDB8A89C9FC3860</transHash><testRequest>0</testRequest><accountNumber>XXXX1111</accountNumber><accountType>Visa</accountType><errors><error><errorCode>27</errorCode><errorText>The transaction has been declined because of an AVS mismatch. The address provided does not match billing address of cardholder.</errorText></error></errors></transactionResponse></createTransactionResponse>""", (AVSError,)),
    ("""<?xml version="1.0" encoding="utf-8"?><createTransactionResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="AnetApi/xml/v1/schema/AnetApiSchema.xsd"><messages><resultCode>Ok</resultCode><message><code>I00001</code><text>Successful.</text></message></messages><transactionResponse><responseCode>2</responseCode><authCode>VIT147</authCode><avsResultCode>Y</avsResultCode><cvvResultCode>N</cvvResultCode><cavvResultCode>2</cavvResultCode><transId>2197488392</transId><refTransID>2197488392</refTransID><transHash>0400A959E9D6FA8BDC548ED8A3CA98FE</transHash><testRequest>0</testRequest><accountNumber>XXXX1111</accountNumber><accountType>Visa</accountType><errors><error><errorCode>65</errorCode><errorText>This transaction has been declined.</errorText></error></errors></transactionResponse></createTransactionResponse>""", (CVVError,)),
    ("""<?xml version="1.0" encoding="utf-8"?><createTransactionResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="AnetApi/xml/v1/schema/AnetApiSchema.xsd"><messages><resultCode>Ok</resultCode><message><code>I00001</code><text>Successful.</text></message></messages><transactionResponse><responseCode>2</responseCode><authCode>M6N6IJ</authCode><avsResultCode>E</avsResultCode><cvvResultCode>N</cvvResultCode><cavvResultCode>2</cavvResultCode><transId>2197488393</transId><refTransID>2197488393</refTransID><transHash>497C75736FAFCECC280122E0E8C72275</transHash><testRequest>0</testRequest><accountNumber>XXXX1111</accountNumber><accountType>Visa</accountType><errors><error><errorCode>45</errorCode><errorText>This transaction has been declined.</errorText></error></errors></transactionResponse></createTransactionResponse>""", (AVSError, CVVError)),
    ("""<?xml version="1.0" encoding="utf-8"?><createTransactionResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="AnetApi/xml/v1/schema/AnetApiSchema.xsd"><messages><resultCode>Error</resultCode><message><code>E00027</code><text>The transaction was unsuccessful.</text></message></messages><transactionResponse><responseCode>3</responseCode><authCode /><avsResultCode>P</avsResultCode><cvvResultCode /><cavvResultCode /><transId>0</transId><refTransID /><transHash>0D70623F0B9C221A0D144496D19B0339</transHash><testRequest>0</testRequest><accountNumber>XXXX1111</accountNumber><accountType>Visa</accountType><errors><error><errorCode>8</errorCode><errorText>The credit card has expired.</errorText></error></errors></transactionResponse></createTransactionResponse>""", (ExpiryError,)),
    ("""<?xml version="1.0" encoding="utf-8"?><createTransactionResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="AnetApi/xml/v1/schema/AnetApiSchema.xsd"><messages><resultCode>Error</resultCode><message><code>E00027</code><text>The transaction was unsuccessful.</text></message></messages><transactionResponse><responseCode>3</responseCode><authCode /><avsResultCode>P</avsResultCode><cvvResultCode /><cavvResultCode /><transId>0</transId><refTransID /><transHash>6A75F1E007C490FFF01C08E1691C28ED</transHash><testRequest>0</testRequest><accountNumber>XXXX1111</accountNumber><accountType /><errors><error><errorCode>6</errorCode><errorText>The credit card number is invalid.</errorText></error></errors></transactionResponse></createTransactionResponse>""", (InvalidCardError,)),
    ("""<?xml version="1.0" encoding="utf-8"?><createTransactionResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="AnetApi/xml/v1/schema/AnetApiSchema.xsd"><messages><resultCode>Error</resultCode><message><code>E00027</code><text>The transaction was unsuccessful.</text></message></messages><transactionResponse><responseCode>3</responseCode><authCode /><avsResultCode>P</avsResultCode><cvvResultCode /><cavvResultCode /><transId>0</transId><refTransID /><transHash>55E1FCDE36ACBC06EC2215592551053F</transHash><testRequest>0</testRequest><accountNumber>XXXX1111</accountNumber><accountType /><errors><error><errorCode>6</errorCode><errorText>The credit card number is invalid.</errorText></error><error><errorCode>8</errorCode><errorText>The credit card has expired.</errorText></error></errors></transactionResponse></createTransactionResponse>""", (InvalidCardError, ExpiryError)),
    ("""<?xml version="1.0" encoding="utf-8"?><createTransactionResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="AnetApi/xml/v1/schema/AnetApiSchema.xsd"><messages><resultCode>Error</resultCode><message><code>E00027</code><text>The transaction was unsuccessful.</text></message></messages><transactionResponse><responseCode>3</responseCode><authCode /><avsResultCode>P</avsResultCode><cvvResultCode /><cavvResultCode /><transId>0</transId><refTransID /><transHash>53120B8E1E241B312894A969EC5C3DAE</transHash><testRequest>0</testRequest><accountNumber>XXXX1111</accountNumber><accountType>Visa</accountType><errors><error><errorCode>5</errorCode><errorText>A valid amount is required.</errorText></error></errors></transactionResponse></createTransactionResponse>""", (InvalidAmountError,)),
    ("""<?xml version="1.0" encoding="utf-8"?><createTransactionResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="AnetApi/xml/v1/schema/AnetApiSchema.xsd"><messages><resultCode>Ok</resultCode><message><code>I00001</code><text>Successful.</text></message></messages><transactionResponse><responseCode>2</responseCode><authCode /><avsResultCode>Y</avsResultCode><cvvResultCode /><cavvResultCode>2</cavvResultCode><transId>2197488395</transId><refTransID /><transHash>B66D4B809F20F8081838EEF369405F5D</transHash><testRequest>0</testRequest><accountNumber>XXXX1111</accountNumber><accountType>Visa</accountType><errors><error><errorCode>2</errorCode><errorText>This transaction has been declined.</errorText></error></errors></transactionResponse></createTransactionResponse>""", (CardDeclinedError,)),
    ("""<?xml version="1.0" encoding="utf-8"?><createTransactionResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="AnetApi/xml/v1/schema/AnetApiSchema.xsd"><messages><resultCode>Error</resultCode><message><code>E00027</code><text>The transaction was unsuccessful.</text></message></messages><transactionResponse><responseCode>3</responseCode><authCode /><avsResultCode>P</avsResultCode><cvvResultCode /><cavvResultCode /><transId>0</transId><refTransID /><transHash>A92198FF2C3182D90959B3A3BFE8FB1D</transHash><testRequest>0</testRequest><accountNumber>XXXX1111</accountNumber><accountType>Visa</accountType><errors><error><errorCode>11</errorCode><errorText>A duplicate transaction has been submitted.</errorText></error></errors></transactionResponse></createTransactionResponse>""", (DuplicateTransactionError,)),
)


GATEWAY_ERRORS = (
    ("""<?xml version="1.0" encoding="utf-8"?><getCustomerProfileResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="AnetApi/xml/v1/schema/AnetApiSchema.xsd"><messages><resultCode>Error</resultCode><message><code>E00040</code><text>The record cannot be found.</text></message></messages></getCustomerProfileResponse>""", CustomerNotFoundError),
    ("""<?xml version="1.0" encoding="utf-8"?><createCustomerProfileResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="AnetApi/xml/v1/schema/AnetApiSchema.xsd"><messages><resultCode>Error</resultCode><message><code>E00013</code><text>Expiration Date is invalid.</text></message></messages><customerPaymentProfileIdList /><customerShippingAddressIdList /><validationDirectResponseList /></createCustomerProfileResponse>""", InvalidCardError),
    ("""<?xml version="1.0" encoding="utf-8"?><createTransactionResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="AnetApi/xml/v1/schema/AnetApiSchema.xsd"><messages><resultCode>Error</resultCode><message><code>E00007</code><text>User authentication failed due to invalid authentication values.</text></message></messages></createTransactionResponse>""", AuthenticationError),
    ("""<?xml version="1.0" encoding="utf-8"?><createCustomerPaymentProfileResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="AnetApi/xml/v1/schema/AnetApiSchema.xsd"><messages><resultCode>Error</resultCode><message><code>E00039</code><text>A duplicate customer payment profile already exists.</text></message></messages><validationDirectResponse>1,1,1,This transaction has been approved.,LG8LF0,Y,2197491038,none,Test transaction for ValidateCustomerPaymentProfile.,0.00,CC,auth_only,none,,,,123 Elm St,,,12345,,,,email@example.com,,,,,,,,,0.00,0.00,0.00,FALSE,none,71B80A36D0E1EE4B15FC337420EC0267,M,2,,,,,,,,,,,XXXX2222,Visa,,,,,,,,,,,,,,,,</validationDirectResponse></createCustomerPaymentProfileResponse>""", DuplicateCardError),
    ("""<?xml version="1.0" encoding="utf-8"?><createCustomerProfileResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="AnetApi/xml/v1/schema/AnetApiSchema.xsd"><messages><resultCode>Error</resultCode><message><code>E00039</code><text>A duplicate record with ID 20464705 already exists.</text></message></messages><customerPaymentProfileIdList /><customerShippingAddressIdList /><validationDirectResponseList /></createCustomerProfileResponse>""", DuplicateCustomerError),
)


def prepare(resp):
    return xml_to_dict(etree.XML(resp))


def test_successful_responses():
    for resp in SUCCESSFUL_RESPONSES:
        gateway.check_for_error(prepare(resp))


def test_payment_errors():
    for resp, errors in PAYMENT_ERRORS:
        with assertRaisesError(*errors):
            gateway.check_for_error(prepare(resp))


def test_gateway_errors():
    for resp, exception in GATEWAY_ERRORS:
        with assertRaises(exception):
            gateway.check_for_error(prepare(resp))
